version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db_planner
      - db_planner_test
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    networks:
      - planner-network

  db_planner:
    container_name: 'db_planner'
    image: postgres
    environment:
      POSTGRES_DB: planner_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - planner-network

  db_planner_test:
    container_name: 'db_planner_test'
    image: postgres
    environment:
      POSTGRES_DB: planner_db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    networks:
      - planner-network

networks:
  planner-network:

volumes:
  pg_data:
